config/routes.rb
Slingshot::Application.routes.draw do

  # personal info 
  get '/profile'      => 'profiles#show', as: 'profile'
  get '/profile/edit' => 'profiles#edit', as: 'edit_profile'
  put '/profile'      => 'profiles#update'
  
  # RESTful device controller
  resources :devices, except: [:destroy]
  
  # location controller
  resource :location, except: [:destroy]
  get '/location/regions/:region_id/cities' => 'locations#get_cities', as: 'cities_region'

  # vpn controller
  resource :vpn, except: [:destroy]
  
  # ActiveAdmin managed AdminUser
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  # Devise managed User
  # 
  # using the relay CAS authentication. see link for more info on setup.
  # https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }


  # Dashboard controller
  get 'dashboard/index'
  get 'dashboard' => 'dashboard#index'

  root :to => 'dashboard#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/area_choices.rb
class AreaChoices < ActiveRecord::Base
  attr_accessible :name
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name, :region_id

  has_many :locations
  has_many :users
  belongs_to :region
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :accessories, :complexity, :drop_off, :os, :password, 
    :pick_up, :status, :type, :user_id, :username, :kind

  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :drop_off, :event_time
  belongs_to :scheduleable, :polymorphic => true

  attr_accessible :event_time, :objective
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city_id, :region_id, :user_id

  validates_presence_of :region

  belongs_to :user
  belongs_to :city
  belongs_to :region
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_one :vpn
  has_many :devices
  has_many :regions
  
  attr_accessible :firstname, 
                  :lastname, 
                  :cell, 
                  :email,
                  :region_sending,
                  :region_destination,
                  :married

  # the user's single sign on info is created or read from the database
  def self.find_or_create_person_from_auth(auth_hash)
    @attributes = {
      firstname: auth_hash.extra.attributes.first.firstName,
      lastname: auth_hash.extra.attributes.first.lastName,
      email: auth_hash.extra.attributes.first.email,
      guid: auth_hash.extra.attributes.first.sooGuid,
      username: auth_hash.extra.attributes.first.username
    }

    @person = Person.find_by_email(@attributes[:email])
    if @person.nil?
      @person = Person.create!(@attributes, without_protection: true)
    end
    return @person
  end

  def sending
    self.regions.where(:sending =>  true).first ? self.regions.where(:sending =>  true).first  : []
  end

  def destination
    self.regions.where(:destination => true).first ? self.regions.where(:destination => true).first : []
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :name

  has_many :locations
  has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable, :registerable, :recoverable 
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:cas]
  
  attr_accessible :email, 
    :password, 
    :password_confirmation, 
    :remember_me, 
    :provider, 
    :uid, 
    :first_name, 
    :last_name, 
    :cell, 
    :room_number, 
    :married, 
    :spouse_fullname, 
    :want_spouse_account, 
    :ccc_account, 
    :non_secure_email,
    :facebook, 
    :google_plus, 
    :city_id
    
  has_many :devices
  has_one :location
  belongs_to :city
  has_one :vpn
  
  def self.find_or_create_from_cas(auth_hash)
    hash_attributes = {
      first_name: auth_hash.extra.attributes.first.firstName,
      last_name: auth_hash.extra.attributes.first.lastName,
      email: auth_hash.extra.attributes.first.email,
      uid: auth_hash.extra.attributes.first.ssoGuid,
      password: Devise.friendly_token[0,20]
    }

    @user = self.find_by_email(hash_attributes[:email])
    @user = self.create!(hash_attributes) if @user.nil?
    @user
  end

  def display_name
    email # || first_name + " " + last_name 
  end


end

app/models/vpn.rb
class Vpn < ActiveRecord::Base
  attr_accessible :password, :user_id, :old_username, :old_password

  belongs_to :user
end

app/models/vpn_account_groups.rb
class VpnAccountGroups < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update    
    @user = current_user
    @user.update_attributes(params[:user])
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to action: :show, notice: 'Personal information was updated' }
        format.json { head :no_content}
      else
        format.html { redirect_to acion: :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end

    end
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/vpn_helper.rb
module VpnHelper
end

app/helpers/vpns_helper.rb
module VpnsHelper
end

app/views/profiles/edit.html.haml
= form_for @user, url: '/profile' do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this vpn from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :cell
    = f.text_field :cell
  
  .field
    = f.label 'Room Number'
    = f.text_field :room_number
  
  .field.form-inline
    = f.label 'Married'
    = f.check_box :married
    
  .field
    = f.label "If married, spouse's fullname"
    = f.text_field :spouse_fullname
    
  .field.form-inline
    = f.label 'Want to add a spouse account'
    = f.check_box :want_spouse_account
    
  .field
    = f.label 'CCC Account Number'
    = f.text_field :ccc_account
  
  .field
    = f.label 'Non-Secure Email'
    = f.text_field :non_secure_email
      
  .field
    = f.label 'Facebook username'
    = f.text_field :facebook
    
  .field 
    = f.label 'Google Plus username'
    = f.text_field :google_plus
  
  .actions
    = f.submit 'Save'

app/views/profiles/show.html.haml
%p 
  %b Cell Number:
  = @user.try(:cell)

%p 
  %b Room Number:
  = @user.try(:room_number)

%p 
  %b Marital Status:
  = @user.married == true ? "Married" : "Single"

%p
  %b Spouse's fullname:
  = @user.spouse_fullname

%p 
  %b Want Spouse Account:
  = @user.want_spouse_account == true ? 'Yes' : 'No'
  
%p 
  %b CCC Account Number:
  = @user.ccc_account

%p 
  %b Non-Secure Email:
  = @user.non_secure_email
    
%p 
  %b Facebook Usernmae:
  = @user.facebook
  
%p 
  %b Google Plus Username:
  = @user.google_plus

.action-links
  = link_to 'Edit', edit_profile_path
  \|
  = link_to 'Dashboard', dashboard_path