config/routes.rb
Slingshot::Application.routes.draw do

  # personal info 
  get '/profile'      => 'profiles#show', as: 'profile'
  get '/profile/edit' => 'profiles#edit', as: 'edit_profile'
  put '/profile'      => 'profiles#update'
  
  # RESTful device controller
  resources :devices, except: [:destroy]
  
  # location controller
  resource :location, except: [:destroy]
  get '/location/regions/:region_id/cities' => 'locations#get_cities', as: 'cities_region'

  # vpn controller
  resource :vpn, except: [:destroy]
  
  # ActiveAdmin managed AdminUser
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  # Devise managed User
  # 
  # using the relay CAS authentication. see link for more info on setup.
  # https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }


  # Dashboard controller
  get 'dashboard/index'
  get 'dashboard' => 'dashboard#index'

  root :to => 'dashboard#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/area_choices.rb
class AreaChoices < ActiveRecord::Base
  attr_accessible :name
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name, :region_id

  has_many :locations
  has_many :users
  belongs_to :region
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :accessories, :complexity, :drop_off, :os, :password, 
    :pick_up, :status, :type, :user_id, :username, :kind

  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :drop_off, :event_time
  belongs_to :scheduleable, :polymorphic => true

  attr_accessible :event_time, :objective
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city_id, :region_id, :user_id

  validates_presence_of :region

  belongs_to :user
  belongs_to :city
  belongs_to :region
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_one :vpn
  has_many :devices
  has_many :regions
  
  attr_accessible :firstname, 
                  :lastname, 
                  :cell, 
                  :email,
                  :region_sending,
                  :region_destination,
                  :married

  # the user's single sign on info is created or read from the database
  def self.find_or_create_person_from_auth(auth_hash)
    @attributes = {
      firstname: auth_hash.extra.attributes.first.firstName,
      lastname: auth_hash.extra.attributes.first.lastName,
      email: auth_hash.extra.attributes.first.email,
      guid: auth_hash.extra.attributes.first.sooGuid,
      username: auth_hash.extra.attributes.first.username
    }

    @person = Person.find_by_email(@attributes[:email])
    if @person.nil?
      @person = Person.create!(@attributes, without_protection: true)
    end
    return @person
  end

  def sending
    self.regions.where(:sending =>  true).first ? self.regions.where(:sending =>  true).first  : []
  end

  def destination
    self.regions.where(:destination => true).first ? self.regions.where(:destination => true).first : []
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :name

  has_many :locations
  has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable, :registerable, :recoverable 
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:cas]
  
  attr_accessible :email, 
    :password, 
    :password_confirmation, 
    :remember_me, 
    :provider, 
    :uid, 
    :first_name, 
    :last_name, 
    :cell, 
    :room_number, 
    :married, 
    :spouse_fullname, 
    :want_spouse_account, 
    :ccc_account, 
    :non_secure_email,
    :facebook, 
    :google_plus, 
    :city_id
    
  has_many :devices
  has_one :location
  belongs_to :city
  has_one :vpn
  
  def self.find_or_create_from_cas(auth_hash)
    hash_attributes = {
      first_name: auth_hash.extra.attributes.first.firstName,
      last_name: auth_hash.extra.attributes.first.lastName,
      email: auth_hash.extra.attributes.first.email,
      uid: auth_hash.extra.attributes.first.ssoGuid,
      password: Devise.friendly_token[0,20]
    }

    @user = self.find_by_email(hash_attributes[:email])
    @user = self.create!(hash_attributes) if @user.nil?
    @user
  end

  def display_name
    email # || first_name + " " + last_name 
  end


end

app/models/vpn.rb
class Vpn < ActiveRecord::Base
  attr_accessible :password, :user_id, :old_username, :old_password

  belongs_to :user
end

app/models/vpn_account_groups.rb
class VpnAccountGroups < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_filter :authenticate_user!  

  # GET /devices
  # GET /devices.json
  def index
    @devices = current_user.devices

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = current_user.devices.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = current_user.devices.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])
    @device.user = current_user

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = current_user.devices.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = current_user.devices.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/vpn_controller.rb
class VpnController < ApplicationController

	before_filter :authenticate

	# standard Rails CRUD based controller

	def index
		redirect_to person_path(session[:person_id])
	end	

	def show
		redirect_to person_path(@person)
	end 

	def new
		@vpn = Vpn.new
	end

	def create
	end

	def edit
		@person ||= get_person
		@vpn = @person.vpn
	end

	def update
		@person ||= get_person
		@vpn = @person.vpn


		respond_to do |format|
			if @vpn.update_attributes(params[:vpn])
				format.html { redirect_to [@person, @vpn], notice: 'VPN password was successsfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @vpn.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@person ||= get_person
		@vpn = @person.vpn
		@vpn.destroy
		redirect_to person_path(@person)
	end

	
	private

	def get_person
		@person = Person.find(session[:person_id])
	end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/vpn_helper.rb
module VpnHelper
end

app/helpers/vpns_helper.rb
module VpnsHelper
end

app/views/devices/_form.html.erb
<!-- form has been revised to be double nested from scaffold form -->
<%= form_for([@person, @device]) do |f| %>		
		<div class="field">
	    <%= f.label :operating_system %><br/>
	    <%= f.select :name, ["PC", "Apple/Mac OSX", "Other"] %>
	  </div>		

		<div class="field">
	    <%= f.label :brand %><br/>
	    <%= f.text_field :brand %>
	  </div>
	  <br/>
	  <b>ATTENTION ALL MAC USERS </b><br/>
If your computer did not come with Lion // Mac OSX 10.7 (IE, Mac 10.6/Snow Leopard, 10.5 Leopard, etc), you need to <br/>
<ol>
	<li>try to "turn on" File Vault 2 full drive encryption <a href="http://support.apple.com/kb/HT4790">(see this Apple help guide)</a></li>
	<li>if necessary go by the Apple store with your backups and have their Mac reinstalled if necessary (Mac Operating System will ).</li>
</ol>

		<br/>
	  <div class="field">
	    <%= f.label :model %><br/>
	    <%= f.text_field :model %>
	  </div>
	  <div class="field">
	    <%= f.label :color %><br/>
	    <%= f.text_field :color %>
	  </div>
	  <div class="field">
	    <%= f.label :Username %>  (if your device has a specific username)<br/>
	    <%= f.text_field :computer_username %>
	  </div>
	  <div class="field">
	    <%= f.label :password %><br/>
	    <%= f.text_field :computer_password %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
<% end %>

app/views/devices/_form.html.haml
= form_for @device do |f|
  - if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "Kind (EG, external number, laptop, iPad, tablet, cell phone)"
    = f.text_field :kind
  .field
    = label_tag "Operating System (EG Mac 10.8, Windows 7, Windows 8)"
    = f.text_field :os
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label "Accessories (EG, charger, flower covered case)"
    = f.text_field :accessories
  .actions
    = f.submit 'Save'

app/views/devices/_list.html.haml
-# expected locals:
-# devices as Array of Devices

%table
  %tr
    %th Kind
    %th Os
    %th Username
    %th Password
    %th Status
    %th Accessories
    %th
    %th
    %th

  - devices.each do |device|
    %tr
      %td= device.try(:kind)
      %td= device.try(:os)
      %td= device.try(:username)
      %td= device.try(:password)
      %td= device.try(:status)
      %td= device.try(:accessories)
      %td= link_to 'Show', device
      %td= link_to 'Edit', edit_device_path(device)

app/views/devices/_nested_form.html.erb
<div name="add-device">
	<%= form_for([@person, @person.devices.build]) do |f| %>
	  <div class="field">
	     <%= f.label "Device Type  " %><%= f.select :name, ["Laptop", "Tablet", "Phone", "iPod/MP3", "Other"] %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
</div>

app/views/devices/_nested_show.html.erb
<h2>Devices</h2>

<h4> Click "Device Description" to add brand/model/etc characteristics for each device</h4>
<table>
<tr>
	<th width="100" align="left"></th>
	<th width="125" align="left"></th>
	<th width="125" align="left"></th>
</tr>

<% @person.devices.each do |device| %>
	<tr>
		<td><%= device.name %></td>
		<td><%= link_to 'Device Description', [device.person, device],
				:get => :show %>
		</td>
		<td><%= button_to 'Delete', [device.person, device], 
				:confirm 	=> 'Sure you want to delete device?',
				:method 	=> :delete %>
		</td>
	</tr>
<% end %>
</table>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%#<%= link_to 'Show', @device %>
<%= link_to 'Back', person_device_path(@device) %>

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Brand</th>
    <th>Model</th>
    <th>Color</th>
    <th>Person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.name %></td>
    <td><%= device.brand %></td>
    <td><%= device.model %></td>
    <td><%= device.color %></td>
    <td><%= device.person %></td>
    
    <td><%= link_to 'Edit', edit_person_device_path(device) %></td>
    <td><%= link_to 'Destroy', person_device, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_person_device_path %>

app/views/devices/index.html.haml
%h1 Devices

= render partial: 'list', locals: {devices: @devices}

.action-links
  = link_to 'Add Device', new_device_path
  \|
  = link_to 'Dashboard', dashboard_path

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>


<!-- ====================================================================== -->
<!-- LINKS -->
<%# <%= link_to 'Edit', edit_device_path(@device) %>
<%# <%= link_to 'Back', devices_path %>
<%= link_to 'My Profile Page', person_path(current_person) %> | 
<%= link_to 'Edit This Device', edit_person_device_path(@person, @device) %>



<!-- ====================================================================== -->
<!-- PERSON -->
<p>
  <b>Person:</b>
  <%= @person.firstname %> <%= @person.lastname %>
</p>


<!-- ====================================================================== -->
<!-- DEVICE ATTRIBUTES -->
<hr>
<h2>Device</h2>
<button><%= @device.name %></button>

<p>
  <b>Type:</b>
  <%= @device.name %>
</p><p>
  <b>Brand:</b>
  <%= @device.brand %>
</p>
<p>
  <b>Model:</b>
  <%= @device.model %>
</p>
<p>
  <b>Color:</b>
  <%= @device.color %>
</p>
<p>
  <b>Username:</b>
  <%= @device.computer_username %>
</p>
<p>
  <b>Password:</b>
  <%= @device.computer_password %>
</p>
<br>

<%= link_to 'Edit This Device', edit_person_device_path(@person, @device) %>

app/views/devices/show.html.haml
%p
  %b User:
  = @device.user.display_name
%p
  %b Username:
  = @device.username
%p
  %b Password:
  = @device.password
%p
  %b Type:
  = @device.kind
%p
  %b Os:
  = @device.os
%p
  %b Accessories:
  = @device.accessories

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path