config/routes.rb
Slingshot::Application.routes.draw do

  # personal info 
  get '/profile'      => 'profiles#show', as: 'profile'
  get '/profile/edit' => 'profiles#edit', as: 'edit_profile'
  put '/profile'      => 'profiles#update'
  
  # RESTful device controller
  resources :devices, except: [:destroy]
  
  # location controller
  resource :location, except: [:destroy]
  get '/location/regions/:region_id/cities' => 'locations#get_cities', as: 'cities_region'

  # vpn controller
  resource :vpn, except: [:destroy]
  
  # ActiveAdmin managed AdminUser
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  # Devise managed User
  # 
  # using the relay CAS authentication. see link for more info on setup.
  # https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }


  # Dashboard controller
  get 'dashboard/index'
  get 'dashboard' => 'dashboard#index'

  root :to => 'dashboard#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/area_choices.rb
class AreaChoices < ActiveRecord::Base
  attr_accessible :name
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name, :region_id

  has_many :locations
  has_many :users
  belongs_to :region
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :accessories, :complexity, :drop_off, :os, :password, 
    :pick_up, :status, :type, :user_id, :username, :kind

  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :drop_off, :event_time
  belongs_to :scheduleable, :polymorphic => true

  attr_accessible :event_time, :objective
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city_id, :region_id, :user_id

  validates_presence_of :region

  belongs_to :user
  belongs_to :city
  belongs_to :region
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_one :vpn
  has_many :devices
  has_many :regions
  
  attr_accessible :firstname, 
                  :lastname, 
                  :cell, 
                  :email,
                  :region_sending,
                  :region_destination,
                  :married

  # the user's single sign on info is created or read from the database
  def self.find_or_create_person_from_auth(auth_hash)
    @attributes = {
      firstname: auth_hash.extra.attributes.first.firstName,
      lastname: auth_hash.extra.attributes.first.lastName,
      email: auth_hash.extra.attributes.first.email,
      guid: auth_hash.extra.attributes.first.sooGuid,
      username: auth_hash.extra.attributes.first.username
    }

    @person = Person.find_by_email(@attributes[:email])
    if @person.nil?
      @person = Person.create!(@attributes, without_protection: true)
    end
    return @person
  end

  def sending
    self.regions.where(:sending =>  true).first ? self.regions.where(:sending =>  true).first  : []
  end

  def destination
    self.regions.where(:destination => true).first ? self.regions.where(:destination => true).first : []
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :name

  has_many :locations
  has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable, :registerable, :recoverable 
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:cas]
  
  attr_accessible :email, 
    :password, 
    :password_confirmation, 
    :remember_me, 
    :provider, 
    :uid, 
    :first_name, 
    :last_name, 
    :cell, 
    :room_number, 
    :married, 
    :spouse_fullname, 
    :want_spouse_account, 
    :ccc_account, 
    :non_secure_email,
    :facebook, 
    :google_plus, 
    :city_id
    
  has_many :devices
  has_one :location
  belongs_to :city
  has_one :vpn
  
  def self.find_or_create_from_cas(auth_hash)
    hash_attributes = {
      first_name: auth_hash.extra.attributes.first.firstName,
      last_name: auth_hash.extra.attributes.first.lastName,
      email: auth_hash.extra.attributes.first.email,
      uid: auth_hash.extra.attributes.first.ssoGuid,
      password: Devise.friendly_token[0,20]
    }

    @user = self.find_by_email(hash_attributes[:email])
    @user = self.create!(hash_attributes) if @user.nil?
    @user
  end

  def display_name
    email # || first_name + " " + last_name 
  end


end

app/models/vpn.rb
class Vpn < ActiveRecord::Base
  attr_accessible :password, :user_id, :old_username, :old_password

  belongs_to :user
end

app/models/vpn_account_groups.rb
class VpnAccountGroups < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	unless current_person
  		redirect_to '/auth/relay'
		else	
  		redirect_to person_path(current_person)
  	end
  end
end

app/controllers/vpn_controller.rb
class VpnController < ApplicationController

	before_filter :authenticate

	# standard Rails CRUD based controller

	def index
		redirect_to person_path(session[:person_id])
	end	

	def show
		redirect_to person_path(@person)
	end 

	def new
		@vpn = Vpn.new
	end

	def create
	end

	def edit
		@person ||= get_person
		@vpn = @person.vpn
	end

	def update
		@person ||= get_person
		@vpn = @person.vpn


		respond_to do |format|
			if @vpn.update_attributes(params[:vpn])
				format.html { redirect_to [@person, @vpn], notice: 'VPN password was successsfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @vpn.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@person ||= get_person
		@vpn = @person.vpn
		@vpn.destroy
		redirect_to person_path(@person)
	end

	
	private

	def get_person
		@person = Person.find(session[:person_id])
	end


end

app/controllers/vpns_controller.rb
class VpnsController < ApplicationController
  before_filter :authenticate_user!

  # GET /vpn
  # GET /vpn.json
  def show
    @vpn = current_user.try(:vpn)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vpn }
    end
  end

  # GET /vpn/new
  # GET /vpn/new.json
  def new
    @vpn = Vpn.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vpn }
    end
  end

  # GET /vpn/edit
  def edit
    @vpn = current_user.vpn
  end

  # POST /vpns
  # POST /vpns.json
  def create
    @vpn = current_user.build_vpn(params[:vpn])

    respond_to do |format|
      if @vpn.save
        format.html { redirect_to vpn_path, notice: 'Vpn was successfully created.' }
        format.json { render json: @vpn, status: :created, location: @vpn }
      else
        format.html { render action: "new" }
        format.json { render json: @vpn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vpns
  # PUT /vpns.json
  def update
    @vpn = current_user.vpn

    respond_to do |format|
      if @vpn.update_attributes(params[:vpn])
        format.html { redirect_to vpn_path, notice: 'Vpn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vpn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vpn
  # DELETE /vpn.json
  def destroy
    @vpn = current_user.vpn
    @vpn.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/vpn_helper.rb
module VpnHelper
end

app/helpers/vpns_helper.rb
module VpnsHelper
end

app/views/vpn/edit.html.erb
<script type="text/javascript"> 

/*
  Password Validator 0.1
  (c) 2007 Steven Levithan <stevenlevithan.com>
  MIT License
*/

function validatePassword (pw, options) {
  // default options (allows any password)
  var o = {
    lower:    1,
    upper:    1,
    alpha:    0, /* lower + upper */
    numeric:  1,
    special:  1,
    length:   [8, Infinity],
    custom:   [ /* regexes and/or functions */ ],
    badWords: ["="],
    badSequenceLength: 0,
    noQwertySequences: false,
    noSequential:      false
  };

  for (var property in options)
    o[property] = options[property];

  var re = {
      lower:   /[a-z]/g,
      upper:   /[A-Z]/g,
      alpha:   /[A-Z]/gi,
      numeric: /[0-9]/g,
      special: /[\W_]/g
    },
    rule, i;

  // enforce min/max length
  if (pw.length < o.length[0] || pw.length > o.length[1])
    return false;

  // enforce lower/upper/alpha/numeric/special rules
  for (rule in re) {
    if ((pw.match(re[rule]) || []).length < o[rule])
      return false;
  }

  // enforce word ban (case insensitive)
  for (i = 0; i < o.badWords.length; i++) {
    if (pw.toLowerCase().indexOf(o.badWords[i].toLowerCase()) > -1)
      return false;
  }

  // enforce the no sequential, identical characters rule
  if (o.noSequential && /([\S\s])\1/.test(pw))
    return false;

  // enforce alphanumeric/qwerty sequence ban rules
  if (o.badSequenceLength) {
    var lower   = "abcdefghijklmnopqrstuvwxyz",
      upper   = lower.toUpperCase(),
      numbers = "0123456789",
      qwerty  = "qwertyuiopasdfghjklzxcvbnm",
      start   = o.badSequenceLength - 1,
      seq     = "_" + pw.slice(0, start);
    for (i = start; i < pw.length; i++) {
      seq = seq.slice(1) + pw.charAt(i);
      if (
        lower.indexOf(seq)   > -1 ||
        upper.indexOf(seq)   > -1 ||
        numbers.indexOf(seq) > -1 ||
        (o.noQwertySequences && qwerty.indexOf(seq) > -1)
      ) {
        return false;
      }
    }
  }

  // enforce custom regex/function rules
  for (i = 0; i < o.custom.length; i++) {
    rule = o.custom[i];
    if (rule instanceof RegExp) {
      if (!rule.test(pw))
        return false;
    } else if (rule instanceof Function) {
      if (!rule(pw))
        return false;
    }
  }

  // great success!
  return true;
}

function testPassword(password){
  var pass = String(password);
  var result = validatePassword(pass)
  
  // good password
  if (result == true) {
    alert('good password');
  };

  // bad password
  if(result == false) {
    alert('bad password');
  };
}
</script>


<h2>Edit VPN Password</h2>

<%= form_for([@person, @vpn]) do |f| %>
  <p>VPN password <b><u>must contain the following 4</u></b> attributes,
    <ul>
      <li>Must <u>not</u> contain an "=" sign</li>
      <li>Must be at least 8 characters long</li>
      <li>Must contain 1 of each of the following 4 categories:</li>
        <ul>
          <li>English uppercase (A through Z)</li>
          <li>Base 10 digits</li>
          <li>English lowercase (a through z)</li>
          <li>Non-alphabetic "special" characters. For example: ~!@#$%^&*()_-+|[]{};.,"'/? and spaces</li>
        </ul>
      <li><b>Must <u>NOT</u> contain the Relay username</b></li>
    </ul>
  </p><br>

  <div class="field">
    <b>VPN Password</b><br>
    <%= f.text_field :simple_password, :onChange => "testPassword(this.value);"%>
  </div>
    

  <p><b>Options</b></p>
  <div class="field">
    Area: <%= f.select :area, @vpn.options_area_choices %>
  </div>
  <div class="field">
    Account Group: <%= f.select :account_group, @vpn.options_vpn_account_groups %>
  </div>
  <div class="field">
    <% if @person.married %><br><b>We suggest this option since you are married.</b><br><% end %>
    Eleazar Option <b>(Mac ONLY!)</b>: 
    <%= f.select :eleazar_account_type, @vpn.options_eleazar_account_types %>
  </div>  

  <br><br><div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>  

app/views/vpns/_form.html.haml
= form_for @vpn, url: '/vpn' do |f|
  - if @vpn.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vpn.errors.count, "error")} prohibited this vpn from being saved:"
      %ul
        - @vpn.errors.full_messages.each do |msg|
          %li= msg

  %li{ id: 'v_equal_sign' }   Must not contain "=" sign
  %li{ id: 'v_length' }       Must exactly 8 characters long
  %li{ id: 'v_uppercase' }    Must contain uppercase characters (A-Z)
  %li{ id: 'v_lowercase' }    Must contain lowercase characters (a-z)
  %li{ id: 'v_digits' }       Must contain Base 10 digits (0-9)
  %li{ id: 'v_symbol' }       Must contain non-alphabetic characters (for example, !@#\$%|\^&*()+-_+={}[];:"'<>,.?~`\/)
  
  %li                         Cannot contain dictonary words (EG, dog, cat, park, shot)
  
  %br
  
  .field
    = f.label :password
    = f.text_field :password
  
  .field
    = f.label '(2nd year STINTers) Previous VPN username'
    = f.text_field :old_username
  
  .field 
    = f.label '(2nd year STINTers) Previous VPN password'
    = f.text_field :old_password
  
  .actions
    = f.submit 'Save', id: 'device_submit'

app/views/vpns/edit.html.haml
%h1 Editing vpn

= render 'form'

= link_to 'Show', vpn_path
\|
= link_to 'Back', vpn_path

app/views/vpns/new.html.haml
%h1 New vpn

= render 'form'

= link_to 'Dashboard', dashboard_path

app/views/vpns/show.html.haml
%p
  %b Password:
  = @vpn.try(:password)

%p
  %b (2nd year STINTers) Old Password:
  = @vpn.try(:old_password)

%p
  %b (2nd year STINTers) Old Username:
  = @vpn.try(:old_username)


- unless @vpn.nil?
  = link_to 'Edit', edit_vpn_path
- else 
  = link_to 'Create', new_vpn_path
  
\|
= link_to 'Dashboard', dashboard_path